### ISSUE TITLE
Controle de versão 

### ISSUE THREAD

**Issue by EvertonMelo** [zcore-coin/zcore-source#1]
ola boa tarde, 

por gentileza se possível informem se existe o controle de versão:
temos apenas o controle: 
https://github.com/zcore-coin/source-code/releases

porém alem da versão:
1.5.1 
mas então onde estão as versões anteriores a isso? 
repositório privado? 
voces poderia confirmar isso? 

se possível informem o pq não estão no Milestones..

**Comment by apollomatheus** [comment]
ISSUE #1 Controle de versão 

As versões liberadas e usadas pelos usuários estão disponíveis nos 2 locais:
https://github.com/zcore-coin/source-code/
https://github.com/zcore-coin/source-code/releases

**Comment by EvertonMelo** [comment]
@apollomatheus 

obrigado pelo retorno.
o link:
https://github.com/zcore-coin/zcore-source/releases 

respondeu parcialmente o meu questionamento.

mas caso nao tenho ficado claro.

a minhas perguntas são:

- vocês utilizam versão Beta e/ou Alfa ou apenas a Final? 
- existe algum impeditivo para rodar versoes antigos do zcore, exemplo: ZCore-1.5.1 ZCore-1.5.2 funcionam de boa na mesma rede, ou apenas quem tem a versão mais recente??

**Comment by apollomatheus** [comment]
@EvertonMelo

As versões são previamente testadas em VPS onde não tem nenhum cliente, não enviamos versão beta até segundo aviso. Talvez em features mais básicas. Pois usuários podem acabar baixando e entrando em forks diferentes, ou até perder a wallet.dat ( nesse caso sempre pedimos para fazer backup antes de atualizar )

A versão ZCore-1.5.1 e ZCore-1.5.2 ainda pertencem ao mesmo fork, então não há pressa para usuários comuns atualizarem.
Apenas anunciamos a necessidade das pools e donos de masternodes atualizarem.

Em relação a sua pergunta sobre a rede:
O que afeta é a formação de superblocos e budgets, as redes ainda continuam na mesma. Isso já foi testado antes para não afetar nenhum usuário.

Mas repetindo, é necessário que as pools e masternodes estejam sempre na versão mais recente.
