### ISSUE TITLE
Sugestão - Evidência Bloco Gênesis

### ISSUE THREAD

**Issue by amaivsimau** [zcore-coin/zcore-source#3]
Fica como sugestão inserir no whitepaper e também uma postagem mais clara no bitcointalk oficial do projeto (ou outro canal oficial que não seja o Facebook) um esclarecimento sobre a _pré mineração_ conforme mencionada nas postagens do projeto.

Eis o bloco gênesis: http://explorer.zcore.cash/api/getblock?hash=00000194d1a0b89f2d487032ca7f3794f9ffe9e073f4b61442e1170e37c7e705

Eis o bloco seguinte: http://explorer.zcore.cash/api/getblock?hash=000001f67999043cec58d08d0732ffcac8d7ac88e1b9f8ed90d0837c5c9763f0

**A partir desses 2 pontos, para um novato as coisas ficam confusas:** http://explorer.zcore.cash/tx/1731bf606b66f66b7fb9190a228a27aa5b29760c938a3d8830d790d48675a780 e http://explorer.zcore.cash/tx/a9ca99e6ad9a1e09fbb2509e37d760af0403400b8a4b2ad60ddb0a0a183b9baa

Pois os esclarecimentos no bitcointalk não estão claros:

https://bitcointalk.org/index.php?topic=3188172.msg34681270#msg34681270

https://bitcointalk.org/index.php?topic=3188172.msg34689134#msg34689134

https://imgur.com/rLGnqTn

https://bitcointalk.org/index.php?topic=3064429.msg31675047#msg31675047

**Comment by apollomatheus** [comment]
Liberação inicial no grupo/canal do Telegram, como demasiadas vezes comentado.
https://t.me/ZCoreCrypto/64

**Comment by amaivsimau** [comment]
@apollomatheus isso significa que será ajustado no paper do projeto?

Visto que ao ver o devido grupo mencionado:

[Zcore (ZCR) - Offical Channel](https://t.me/ZCoreCrypto/64)

Consta criação em 21-02-2018 e a primeira postagem em 15-03-2018 16:08:28

Entretanto, a devida postagem diz que o lançamento oficial foi na data de 19-03-2018. Mas como podemos ver, já se tem blocos na rede antes do lançamento oficial, portanto minha dúvida é se será ajustado isso no paper? 

![image](https://user-images.githubusercontent.com/7751366/41980688-7a142b1c-79fd-11e8-9713-7e1d11554309.png)


**Obrigado desde já.**

**Comment by mosqueiro** [comment]
@amaivsimau Você está se confundindo, veja corretamente seu print.
O Canal foi criado dia 21/02 para que ninguém usasse o username do Telegram.
Liberamos a moeda no mesmo canal, onde mais de 3mil pessoas já faziam parte do grupo do Telegram no dia 15/03 (vide postagem) com o pool de mineração, e a moeda foi lançada dia 19/03, tudo informado no canal.

O que você acha que deve ser ajustado no paper, se tem algo a acrescentar estaremos à disposição!

**Comment by amaivsimau** [comment]
Obrigado pelo retorno @mosqueiro 

Pode ser que me expressei de forma incompleta. O que voce descreveu, acima é exatamente a evidência que postei (até com a imagem).

> Consta criação **(do grupo)** em 21-02-2018 e a primeira postagem em 15-03-2018 16:08:28 **(destacados em amarelo na imagem)**.

Eu particularmente não vejo problema em existir pré mineração, desde que tenha isso descrito, no entanto o paper do projeto menciona que não houve pré mineração correto?
Mas ao observar o blockchain e as postagens dos fóruns não me passou credibilidade para contribuir ainda mais com o projeto.

Por isso abri a issue para que coloquem os links do bloco gênesis e todas essas informações descritas dessa issue no paper (ajudar os novatos sobre). Pois alguém sem conhecimento do ramo poderá questionar sobre, inclusive como descrito acima que houve gasto para entrada em exchanges, masternodes e afins, mesmo assim existe margem para as seguintes questões **(não precisa responder)**:

- Houve privateSend nessas transações?
- Existem postagens nos fóruns oficiais ou Bitcointalk sobre essas ações?
 - Houve proof of burn? Se sim quais as transações do método?

Aguardarei a nova versão do paper e darei um feedback sobre caso seja necessário. Obrigado mais uma vez pelo suporte :)
