### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by pro202** [zcore-coin/zcore-source#6]
Hi admin zcore, i download wallet but wallet can't be open by window 10

**Comment by apollomatheus** [comment]
Hi,

Please report the error on issues.
Or send me all detailed info in email.

Em sáb, 8 de set de 2018 às 19:06, pro202 <notifications@github.com>
escreveu:

**Comment by apollomatheus** [comment]
Please specify the error.

**Comment by apollomatheus** [comment]
Closed - no details provided.
